language: perl
sudo: false
perl:
  - "5.14"
  - "5.16"
  - "5.18"
  - "5.20"

before_script:
  - cpanm --quiet --notest --skip-satisfied Devel::Cover Devel::Cover::Report::Codecov
  - cpanm -n Devel::Cover::Report::Coveralls

script:
  - perl Build.PL
  - ./Build build
  - cover -test

after_success:
  - cover -report codecov
  - cover -report coveralls
