language: perl
sudo: false

perl:
  - "5.24"

env:
  AUTHOR_TESTING: 1
before_install:
  - cpanm --quiet --notest --skip-satisfied Devel::Cover Devel::Cover::Report::Codecov
  - cpanm --quiet --notest --skip-satisfied --installdeps --with-recommend . || cat ~/.cpanm/build.log"
  - cover -delete
after_failure:
  - "cat ~/.cpanm/build.log"
script:
  - perl Build.PL
  - ./Build build
  - cover -test
after_success:
  - cover -report codecov
