language: perl
sudo: false

perl:
  - "5.22"
  - "5.24"

env:
  AUTHOR_TESTING: 1
before_install:
  - git clone git://github.com/travis-perl/helpers ~/travis-perl-helpers
  - source ~/travis-perl-helpers/init --auto
  - cpanm --quiet --notest --skip-satisfied Devel::Cover Devel::Cover::Report::Codecov
  - cpanm --quiet --notest --skip-satisfied --installdeps --with-recommend .
  - cover -delete
script:
  - perl Build.PL
  - ./Build build
  - cover -test
after_success:
  - cover -report codecov
